import { CompanyPublicH2ContractError } from './contractErrors'
import { BLOCK_IDS, object, type Obj } from './contractSchema'
import { isStrictJsonInteger, isStrictJsonObject, type StrictJsonValue } from './strictJson'

const BLOCK_ORDER=['hero_status','narrative','in_page_navigation','requisites','finance_f1_liquidity','finance_f2_funding','finance_f3_growth','finance_f4_profit_per_100','finance_f5_yearly_table','arbitration_a1_activity','arbitration_a2_roles','arbitration_a3_outcomes','arbitration_a4_case_amounts','arbitration_a5_opponents','sources_limitations','neutral_actions'] as const
const COVERAGE=['requisites','narrative','finance_f1','finance_f2','finance_f3','finance_f4','finance_f5','arbitration_a1','arbitration_a2','arbitration_a3','arbitration_a4','arbitration_a5','sources_limitations'] as const
const fail=(m:string):never=>{throw new CompanyPublicH2ContractError(m)}
const rec=(v:StrictJsonValue|undefined,p:string):Obj=>object(v,p)
const s=(v:StrictJsonValue|undefined,p:string):string=>typeof v==='string'?v:fail(p+' must be string')
const i=(v:StrictJsonValue|undefined,p:string):bigint=>{const item=isStrictJsonInteger(v)?v:fail(p+' must be integer');return item.value}
const ar=(v:StrictJsonValue|undefined,p:string):readonly StrictJsonValue[]=>Array.isArray(v)?v:fail(p+' must be array')
const same=(left:readonly unknown[],right:readonly unknown[])=>left.length===right.length&&left.every((value,index)=>value===right[index])
const unique=(items:readonly string[])=>new Set(items).size===items.length

type Dec=Readonly<{ coefficient:bigint; scale:bigint }>
function decimal(raw:string,p:string):Dec {
  if(!/^-?(?:0|[1-9][0-9]*)(?:\.[0-9]*[1-9])?$/.test(raw))fail(`${p} invalid decimal`)
  const negative=raw.startsWith('-'), body=negative?raw.slice(1):raw, [whole,fraction='']=body.split('.')
  return {coefficient:(negative?-1n:1n)*BigInt(`${whole}${fraction}`),scale:BigInt(fraction.length)}
}
function pow10(scale:bigint):bigint { let r=1n;for(let n=0n;n<scale;n+=1n)r*=10n;return r }
function cmp(a:Dec,b:Dec):number { const scale=a.scale>b.scale?a.scale:b.scale, x=a.coefficient*pow10(scale-a.scale),y=b.coefficient*pow10(scale-b.scale);return x===y?0:x<y?-1:1 }
function add(a:Dec,b:Dec):Dec { const scale=a.scale>b.scale?a.scale:b.scale;return {coefficient:a.coefficient*pow10(scale-a.scale)+b.coefficient*pow10(scale-b.scale),scale} }
function mul(a:Dec,b:bigint):Dec{return {coefficient:a.coefficient*b,scale:a.scale}}
function div(a:Dec,b:bigint):Dec{return {coefficient:a.coefficient,scale:a.scale+BigInt(b.toString().length-1)}}
function d(v:StrictJsonValue|undefined,p:string):Dec{return decimal(s(v,p),p)}
function money(v:StrictJsonValue|undefined,p:string):void {const x=rec(v,p), source=d(x.source_thousand_decimal,`${p}.source_thousand_decimal`),rub=d(x.rub_decimal,`${p}.rub_decimal`),million=d(x.million_decimal,`${p}.million_decimal`);if(cmp(rub,mul(source,1000n))!==0||cmp(million,div(source,1000n))!==0)fail(`${p} finance money units do not agree`)}
function axis(v:StrictJsonValue|undefined,p:string):void {const x=rec(v,p),a=d(x.axis_min_decimal,`${p}.axis_min_decimal`),b=d(x.axis_max_decimal,`${p}.axis_max_decimal`);if(cmp(a,{coefficient:0n,scale:0n})>0||cmp(b,{coefficient:0n,scale:0n})<0||cmp(a,b)>0)fail(`${p} axis must contain zero and be ordered`)}
function scope(v:StrictJsonValue|undefined,p:string):void {const x=rec(v,p);if(i(x.shown,`${p}.shown`) !== (i(x.eligible_total,`${p}.eligible_total`)<20n?i(x.eligible_total,`${p}.eligible_total`):20n))fail(`${p} invalid shown count`)}
function nfc(value:StrictJsonValue,path='root'):void {if(typeof value==='string'){if(value!==value.normalize('NFC')||[...value].some(c=>{const n=c.codePointAt(0)!;return n>=0xd800&&n<=0xdfff}))fail(`${path} must be NFC Unicode scalars`);return}if(Array.isArray(value)){value.forEach((x,n)=>nfc(x,`${path}[${n}]`));return}if(isStrictJsonObject(value)){for(const [k,x] of Object.entries(value)){if(k!==k.normalize('NFC'))fail(`${path} key must be NFC`);nfc(x,`${path}.${k}`)}}}
function detailScopes(value:StrictJsonValue,path='root'):void {if(Array.isArray(value)){value.forEach((x,n)=>detailScopes(x,`${path}[${n}]`));return}if(isStrictJsonObject(value)){if(Object.hasOwn(value,'population_scope')&&Object.hasOwn(value,'eligible_total')&&Object.hasOwn(value,'shown')&&Object.hasOwn(value,'cap')&&Object.hasOwn(value,'rows_received')&&Object.hasOwn(value,'source_total'))scope(value,path);Object.entries(value).forEach(([k,x])=>detailScopes(x,`${path}.${k}`))}}
function axes(value:StrictJsonValue,path='root'):void {if(Array.isArray(value)){value.forEach((x,n)=>axes(x,`${path}[${n}]`));return}if(isStrictJsonObject(value)){if(Object.hasOwn(value,'axis_min_decimal')&&Object.hasOwn(value,'axis_max_decimal'))axis(value,path);Object.entries(value).forEach(([k,x])=>axes(x,`${path}.${k}`))}}
function monies(value:StrictJsonValue,path='root'):void {if(Array.isArray(value)){value.forEach((x,n)=>monies(x,`${path}[${n}]`));return}if(isStrictJsonObject(value)){if(Object.hasOwn(value,'source_thousand_decimal')&&Object.hasOwn(value,'rub_decimal')&&Object.hasOwn(value,'million_decimal')&&Object.hasOwn(value,'unit_id'))money(value,path);Object.entries(value).forEach(([k,x])=>monies(x,`${path}.${k}`))}}

function finance(root:Obj):void {
 const blocks=rec(root.blocks,'blocks')
 const f1=blocks.finance_f1
 if(f1!==null){const x=rec(f1,'finance_f1');if(!same(ar(x.segments,'finance_f1.segments').map((z,n)=>s(rec(z,`finance_f1.segments[${n}]`).metric_id,'metric_id')),['1250','1240','1230','1500']))fail('F1 segments are fixed');let available={coefficient:0n,scale:0n};for(const k of ['cash_1250','investments_1240','receivables_1230'] as const)available=add(available,d(rec(x[k],`finance_f1.${k}`).source_thousand_decimal,`finance_f1.${k}.source_thousand_decimal`));if(cmp(available,d(rec(x.available_without_inventory,'finance_f1.available_without_inventory').source_thousand_decimal,'finance_f1.available_without_inventory.source_thousand_decimal'))!==0||cmp(add(available,{coefficient:-d(rec(x.short_liabilities_1500,'finance_f1.short_liabilities_1500').source_thousand_decimal,'finance_f1.short_liabilities_1500.source_thousand_decimal').coefficient,scale:d(rec(x.short_liabilities_1500,'finance_f1.short_liabilities_1500').source_thousand_decimal,'finance_f1.short_liabilities_1500.source_thousand_decimal').scale}),d(rec(x.difference,'finance_f1.difference').source_thousand_decimal,'finance_f1.difference.source_thousand_decimal'))!==0)fail('F1 arithmetic mismatch')}
 const f2=blocks.finance_f2
 if(f2!==null){const x=rec(f2,'finance_f2'), anchor=i(x.anchor_year,'finance_f2.anchor_year'),start=i(x.window_start_year,'finance_f2.window_start_year');if(start!==anchor-6n||!same(ar(x.periods,'finance_f2.periods').map((q,n)=>i(rec(q,`finance_f2.periods[${n}]`).year,'year')),Array.from({length:7},(_,n)=>start+BigInt(n))))fail('F2 periods must be seven ascending years');ar(x.periods,'finance_f2.periods').forEach((q,n)=>{const p=rec(q,`finance_f2.periods[${n}]`),state=s(p.state,'state'),mode=s(p.mode,'mode'),moneyFields=['equity_1300','long_liabilities_1400','short_liabilities_1500','debt','denominator'],derived=[p.equity_share_decimal,p.debt_share_decimal,p.axis,...ar(p.geometry_by_metric,'geometry_by_metric')],allMoney=moneyFields.every(k=>p[k]!==null),anyMoney=moneyFields.some(k=>p[k]!==null),allDerived=derived.every(z=>z!==null),anyDerived=derived.some(z=>z!==null);if(state==='gap'&&(anyMoney||mode!=='unavailable'||anyDerived))fail('F2 gap cannot infer values');if(state==='denominator_unavailable'&&(!allMoney||mode!=='unavailable'||anyDerived))fail('F2 denominator shape mismatch');if(state==='available'&&(!allMoney||mode==='unavailable'||!allDerived))fail('F2 available shape mismatch')})}
 const f3=blocks.finance_f3
 if(f3!==null){const x=rec(f3,'finance_f3'),anchor=i(x.anchor_year,'finance_f3.anchor_year'),start=i(x.window_start_year,'finance_f3.window_start_year');if(start!==anchor-6n||!same(ar(x.points,'finance_f3.points').map((q,n)=>i(rec(q,`finance_f3.points[${n}]`).year,'year')),Array.from({length:7},(_,n)=>start+BigInt(n)))||s(rec(x.revenue_summary,'finance_f3.revenue_summary').metric_id,'metric_id')!=='revenue_2110'||s(rec(x.assets_summary,'finance_f3.assets_summary').metric_id,'metric_id')!=='assets_1600')fail('F3 shape mismatch')}
 const f4=blocks.finance_f4
 if(f4!==null){const x=rec(f4,'finance_f4'),derived=[x.revenue_per_100_decimal,x.gross_per_100_decimal,x.operating_per_100_decimal,x.net_per_100_decimal,x.axis,...ar(x.geometry_by_metric,'finance_f4.geometry_by_metric')];if((s(x.mode,'finance_f4.mode')==='per_100')!==derived.every(z=>z!==null))fail('F4 denominator shape mismatch')}
 const f5=blocks.finance_f5
 if(f5!==null){const x=rec(f5,'finance_f5'),anchor=i(x.anchor_year,'finance_f5.anchor_year'),years=ar(x.years,'finance_f5.years').map((q,n)=>i(q,`finance_f5.years[${n}]`)),expected=Array.from({length:7},(_,n)=>anchor-6n+BigInt(n)),ids=['2110','1600','1250','1240','1230','1210','1500','1300','2400'];if(!same(years,expected)||!same(ar(x.rows,'finance_f5.rows').map((q,n)=>s(rec(q,`finance_f5.rows[${n}]`).metric_id,'metric_id')),ids))fail('F5 shape mismatch');ar(x.rows,'finance_f5.rows').forEach((q,n)=>{if(!same(ar(rec(q,`finance_f5.rows[${n}]`).cells,'cells').map((z,j)=>i(rec(z,`cell[${j}]`).year,'year')),years))fail('F5 cell years mismatch')})}
}

export function validateCompanyPublicH2Semantics(root:Obj):void {
 nfc(root); monies(root); axes(root); detailScopes(root); finance(root)
 const identity=rec(root.identity,'identity'), req=rec(rec(root.blocks,'blocks').requisites,'blocks.requisites')
 const owners=ar(req.owners,'owners');owners.forEach((q,n)=>{const x=rec(q,`owners[${n}]`);if((x.share_percent_decimal===null)!==(x.share_display===null))fail('owner share fields must co-occur')})
 if(ar(req.additional_activities,'additional_activities').some((q,n)=>rec(q,`additional_activities[${n}]`).is_primary===true))fail('invalid requisites ordering')
 const modes=ar(req.tax_modes,'tax_modes').map((q,n)=>s(rec(q,`tax_modes[${n}]`).mode_id,'mode_id'));if(!same(modes,[...modes].sort()))fail('invalid requisites ordering')
 const narrative=rec(root.narrative,'narrative'),statement=ar(narrative.statement_ids,'statement_ids').map((q,n)=>s(q,`statement_ids[${n}]`));if(!unique(statement))fail('invalid narrative')
 ar(narrative.comments,'comments').forEach((q,n)=>{const ids=ar(rec(q,`comments[${n}]`).evidence_ids,'evidence_ids').map((z,j)=>s(z,`evidence_ids[${j}]`));if(!unique(ids))fail('invalid chart comment')})
 if(!same(ar(root.block_order,'block_order').map((q,n)=>s(q,`block_order[${n}]`)),BLOCK_ORDER))fail('invalid block order')
 const coverage=ar(root.coverage,'coverage');if(!same(coverage.map((q,n)=>s(rec(q,`coverage[${n}]`).block_id,'block_id')),COVERAGE))fail('invalid coverage order')
 coverage.forEach((q,n)=>{const x=rec(q,`coverage[${n}]`),codes=ar(x.limitation_codes,'limitation_codes').map((z,j)=>s(z,`code[${j}]`));if(!unique(codes)||(s(x.state,'state')!=='available'&&codes.length===0))fail('invalid coverage')})
 const limitations=ar(root.limitations,'limitations'),known=limitations.map((q,n)=>s(rec(q,`limitations[${n}]`).code,'code'));if(!unique(known))fail('invalid limitation');limitations.forEach((q,n)=>{const x=rec(q,`limitations[${n}]`);if(x.block_id!==null&&!BLOCK_IDS.includes(s(x.block_id,'limitation.block_id') as typeof BLOCK_IDS[number]))fail('invalid limitation')});coverage.forEach((q,n)=>ar(rec(q,`coverage[${n}]`).limitation_codes,'limitation_codes').forEach((z,j)=>{if(!known.includes(s(z,`coverage[${n}].limitation_codes[${j}]`)))fail('coverage references missing limitation')}))
 const sources=ar(root.sources,'sources').map((q,n)=>s(rec(q,`sources[${n}]`).dataset,'dataset'));if(sources.length<1||sources.length>3||!same(sources,['counterparty','finance','arbitration'].slice(0,sources.length)))fail('invalid source order')
 const version=s(root.report_version,'report_version'),cap=s(root.snapshot_capability,'snapshot_capability'),scopeValue=s(root.projection_scope,'projection_scope');if((version==='3')!==(cap==='card_v2')||((version==='1'||version==='2')&&root.indexable===true)||(root.indexable===true&&scopeValue!=='active_publication'))fail('invalid version/indexability')
 const canonical=s(root.canonical_path,'canonical_path'),inn=s(identity.inn,'identity.inn');if(!new RegExp(`^/company/${inn}-[a-z0-9]+(?:-[a-z0-9]+)*$`).test(canonical))fail('canonical path does not bind INN')
 const actions=ar(root.actions,'actions'),crumbs=ar(root.breadcrumbs,'breadcrumbs');if(s(rec(actions[0],'actions[0]').action_id,'action_id')!=='check_another_company'||s(rec(actions[0],'actions[0]').label,'label')!=='Проверить другую компанию'||s(rec(actions[0],'actions[0]').path,'path')!=='/'||s(rec(actions[1],'actions[1]').action_id,'action_id')!=='prepare_claim'||s(rec(actions[1],'actions[1]').label,'label')!=='Подготовить претензию'||s(rec(crumbs[0],'breadcrumbs[0]').label,'label')!=='Главная'||s(rec(crumbs[0],'breadcrumbs[0]').path,'path')!=='/'||rec(crumbs[0],'breadcrumbs[0]').current!==false||rec(crumbs[1],'breadcrumbs[1]').current!==true||s(rec(crumbs[1],'breadcrumbs[1]').label,'label')!==s(identity.display_name,'identity.display_name')||s(rec(crumbs[1],'breadcrumbs[1]').path,'path')!==canonical)fail('invalid navigation')
 const claim=`/claims?report_id=${s(root.report_id,'report_id')}`;if(s(rec(actions[1],'actions[1]').path,'path')!==claim||s(rec(root.primary_claim_cta,'primary_claim_cta').path,'primary_claim_cta.path')!==claim)fail('invalid Claims cross-binding')
 const blocks=rec(root.blocks,'blocks');for(const id of COVERAGE.slice(2,-1)){const blockKey=id as keyof typeof blocks;if((s(rec(coverage.find(q=>s(rec(q,'coverage').block_id,'block_id')===id),'coverage').state,'state')==='available') !== (blocks[blockKey]!==null))fail('coverage and block disagree')}
}
